---
- name: Ensure that the jailkit package is installed
  tags: jailkit
  become: true
  yum:
    enablerepo: lux
    name: jailkit
    state: present
  register: jailkit_yum

- name: Applying jailkit configurations
  tags: jailkit
  become: true
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - { src: jk_check.ini.j2, dest: /etc/jailkit/jk_check.ini }
    - { src: jk_chrootsh.ini.j2, dest: /etc/jailkit/jk_chrootsh.ini }
    - { src: jk_init.ini.j2, dest: /etc/jailkit/jk_init.ini }
    - { src: jk_lsh.ini.j2, dest: /etc/jailkit/jk_lsh.ini }
    - { src: jk_socketd.ini.j2, dest: /etc/jailkit/jk_socketd.ini }
    - { src: jk_uchroot.ini.j2, dest: /etc/jailkit/jk_uchroot.ini }
    - { src: jk_update.ini.j2, dest: /etc/jailkit/jk_update.ini }
  when: jailkit_yum|success

- block:
    - name: Creating chroot directory tree (if applicable)
      file:
        path: "{{ item.path }}"
        owner: "{{ item.owner }}"
        group: "{{ item.group }}"
        mode: "{{ item.mode }}"
        recurse: yes
        state: directory
      with_items: "{{ jk_create }}"
      when:
        - item.path is defined
        - item.owner is defined
        - item.group is defined
        - item.mode is defined

    - name: Executing jk_init to initialize jails (if applicable)
      shell: |
        jk_init {{ item.path }} {{ item.profile }}
      with_items: "{{ jk_create }}"
      when:
        - item.path is defined
        - item.profile is defined
  tags: jailkit
  become: true
  when: jk_create is defined
...
